### ISSUE TITLE
doesn't work with shaderpacks 

### ISSUE THREAD

**Issue by OrkunYaman** [grondag/darkness#10]
doesn't work with shaderpacks ?? any ideas ???

**Comment by ChristopherTheBoss** [comment]
Makes sense. I downloaded the mod but won't be installing for this reason. It's a great idea, but for this to work for a shader pack, it would need its own implementation (I think so anyways).

**Comment by ChristopherTheBoss** [comment]
@OrkunYaman Complementary shaders allow you to adjust minimum brightness (for darker caves) and nighttime darkness, either as an absolute value or as related to the fullness of the moon. You can adjust shader settings by getting the latest beta of Iris or by just using Optifine.

**Comment by Reeses-Puffs** [comment]
dude this doesn't work with optifine shaderpacks. it is explicitly stated that it only works with it's own shaderpack system.
@grondag pls close

**Comment by Reeses-Puffs** [comment]
oops I thought this was a canvas issue
my bad

**Comment by grondag** [comment]
This mod works by manipulating the lightmap texture.  Any shader pack or mod that circumvents the light map and computes ambient lighting directly will probably ignore it.  For those mods, your best bet is to ask their creator to add a similar feature.
