### ISSUE TITLE
Hi my pls help

### ISSUE THREAD

**Issue by MaloTV** [grondag/darkness#14]
when im starting my game it says Zombie Awareness hast calass loading errors 
java.lang.NoClassDefFoundError: com/corosus/modconfig/iConfigCategory 
What Can i do about it that its working
![HELPP THX](https://user-images.githubusercontent.com/70515562/153706135-ecc28e39-d013-4eaf-b1c8-56af21dc4fb0.png)
?

**Comment by grondag** [comment]
Hello, this does not appear to be related to True Darkness.
