### ISSUE TITLE
Lighting in the End is Always Dark

### ISSUE THREAD

**Issue by IAmSneak** [grondag/darkness#2]
I set dark_end to false in the config and it still appears dark in the end.
![2020-06-01_19 48 40](https://user-images.githubusercontent.com/66091019/83465148-f1cfa180-a440-11ea-9af9-c663371c9f76.png)

**Comment by IAmSneak** [comment]
darkness-mc115-1.3.18.jar

**Comment by grondag** [comment]
Fixed in build 25, uploaded to Curse just now.  Thank you for the defect report.
