### ISSUE TITLE
[SUGGESTION] Server-Side Integration

### ISSUE THREAD

**Issue by Camawama** [grondag/darkness#21]
HUGE REQUEST, QUITE IMPORTANT.

Please make this a Server-Side mod. Not because the server needs it to work, but to prevent people from uninstalling it on modpacks to gain an unfair advantage on the server.

People can easily remove this mod from the list and walk around caves like normal while everyone else is stuck in darkness. That needs to be fixed.

**Comment by grondag** [comment]
I understand the desire for this request, but there is no practical way of doing it because of how MC multiplayer works.

**Comment by Aceplante** [comment]
Just have it require the players to have it client side when installed on server.?
